# Generated by Django 5.0.2 on 2025-05-31 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="活动标题")),
                (
                    "sport_type",
                    models.CharField(
                        choices=[
                            ("basketball", "篮球"),
                            ("football", "足球"),
                            ("pingpong", "乒乓球"),
                            ("running", "跑步"),
                            ("volleyball", "排球"),
                        ],
                        max_length=20,
                        verbose_name="运动类型",
                    ),
                ),
                ("date", models.DateField(verbose_name="活动日期")),
                ("time", models.TimeField(verbose_name="活动时间")),
                ("location", models.CharField(max_length=200, verbose_name="活动地点")),
                ("min_players", models.IntegerField(verbose_name="最少人数")),
                ("max_players", models.IntegerField(verbose_name="最多人数")),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("beginner", "新手友好"),
                            ("intermediate", "有一定基础"),
                            ("advanced", "有较多经验"),
                            ("expert", "高手级别"),
                        ],
                        max_length=20,
                        verbose_name="技能水平",
                    ),
                ),
                ("description", models.TextField(verbose_name="活动描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起人",
                    ),
                ),
            ],
            options={
                "verbose_name": "运动组队",
                "verbose_name_plural": "运动组队",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="teams.team",
                        verbose_name="组队",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joined_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "组队成员",
                "verbose_name_plural": "组队成员",
                "unique_together": {("team", "user")},
            },
        ),
        migrations.CreateModel(
            name="TeamTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="标签名")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="teams.team",
                        verbose_name="组队",
                    ),
                ),
            ],
            options={
                "verbose_name": "组队标签",
                "verbose_name_plural": "组队标签",
                "unique_together": {("team", "name")},
            },
        ),
    ]
