# Generated by Django 5.0.3 on 2025-06-09 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="活动标题")),
                ("location", models.CharField(max_length=200, verbose_name="地点")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("target_number", models.PositiveIntegerField(verbose_name="目标人数")),
                (
                    "current_number",
                    models.PositiveIntegerField(default=0, verbose_name="当前人数"),
                ),
                (
                    "sport_type",
                    models.CharField(
                        choices=[
                            ("basketball", "篮球"),
                            ("football", "足球"),
                            ("pingpong", "乒乓球"),
                            ("running", "跑步"),
                            ("volleyball", "排球"),
                        ],
                        max_length=20,
                        verbose_name="运动类型",
                    ),
                ),
                ("requirements", models.TextField(blank=True, verbose_name="需求")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "组队信息",
                "verbose_name_plural": "组队信息",
                "db_table": "teams_team",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="报名时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("joined", "已加入"), ("left", "已退出")],
                        default="joined",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="teams.team",
                        verbose_name="组队",
                    ),
                ),
            ],
            options={
                "verbose_name": "报名记录",
                "verbose_name_plural": "报名记录",
                "db_table": "teams_registration",
                "ordering": ["-registration_time"],
                "unique_together": {("user", "team")},
            },
        ),
    ]
