# Generated by Django 5.0.3 on 2025-06-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="sport_type",
            field=models.CharField(
                choices=[
                    ("basketball", "篮球"),
                    ("football", "足球"),
                    ("pingpong", "乒乓球"),
                    ("running", "跑步"),
                    ("volleyball", "排球"),
                    ("badminton", "羽毛球"),
                    ("tennis", "网球"),
                    ("fitness", "有氧健身"),
                    ("swimming", "游泳"),
                ],
                max_length=20,
                verbose_name="运动类型",
            ),
        ),
    ]
